
server:
  port: 8081
  
  
spring:
  application:
    name: API-GATEWAY
    
    
  cloud:
    gateway:
      routes:
      - id: DOCTOR-SERVICE
        uri:
          lb://DOCTOR-SERVICE
        predicates:
        - Path=/doctor/**
          
          
      - id: PATIENT-SERVICE
        uri:
           lb://PATIENT-SERVICE
        predicates:
        - Path=/patient/**  
      
      globalcors:
        cors-configurations:
           '[/**]':
             allowed-origins: '*'
             allowed-headers:
                - Content-Type
             allowed-methods:
                - GET
                - POST
                - PUT
                - DELETE
           
      

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    
 
    serviceUrl:
        defaultZone: http://localhost:8761/eureka 
  instance:
      preferIpAddress: true     
 
      hostname: localhost  
  
        
        